name: ns_intl_phone_input
description: Package for international phone number input with country code
version: 0.0.1
homepage: https://github.com/Rajan-Metaliya/ns_intl_phone_inpu
repository: https://github.com/Rajan-Metaliya/ns_intl_phone_inpu
issue_tracker: https://github.com/Rajan-Metaliya/ns_intl_phone_inpu/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: "AppleColorEmoji"
      fonts:
        - asset: assets/fonts/apple_color_emoji.ttf
