name: ns_intl_phone_input tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5" # Adjust to your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Test Suite with Coverage
        run: flutter test --coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Dart Analysis
        run: flutter analyze --fatal-infos

      - name: Check Code Formatting
        run: dart format -o none --set-exit-if-changed .
