name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Remove previous coverage reports
        run: rm -rf coverage

      - name: Run tests with coverage
        uses: flutter test --coverage

      - name: Generate coverage reports
        run: genhtml coverage/lcov.info -o coverage/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Rajan-Metaliya/ns_intl_phone_input
